insert into public.exercises (name, muscle_group, equipment) values
  ('Bench Press', 'chest', 'barbell'),
  ('Incline Bench Press', 'chest', 'barbell'),
  ('Dumbbell Press', 'chest', 'dumbbell'),
  ('Push Up', 'chest', 'bodyweight'),
  ('Chest Fly', 'chest', 'dumbbell'),
  ('Pull Up', 'back', 'bodyweight'),
  ('Lat Pulldown', 'back', 'cable'),
  ('Barbell Row', 'back', 'barbell'),
  ('Seated Cable Row', 'back', 'cable'),
  ('Deadlift', 'back', 'barbell'),
  ('Overhead Press', 'shoulders', 'barbell'),
  ('Lateral Raise', 'shoulders', 'dumbbell'),
  ('Front Raise', 'shoulders', 'dumbbell'),
  ('Face Pull', 'shoulders', 'cable'),
  ('Barbell Curl', 'biceps', 'barbell'),
  ('Dumbbell Curl', 'biceps', 'dumbbell'),
  ('Hammer Curl', 'biceps', 'dumbbell'),
  ('Tricep Pushdown', 'triceps', 'cable'),
  ('Skull Crusher', 'triceps', 'barbell'),
  ('Dips', 'triceps', 'bodyweight'),
  ('Back Squat', 'legs', 'barbell'),
  ('Front Squat', 'legs', 'barbell'),
  ('Leg Press', 'legs', 'machine'),
  ('Lunge', 'legs', 'dumbbell'),
  ('Leg Curl', 'legs', 'machine'),
  ('Leg Extension', 'legs', 'machine'),
  ('Calf Raise', 'legs', 'machine'),
  ('Romanian Deadlift', 'legs', 'barbell'),
  ('Plank', 'core', 'bodyweight'),
  ('Crunch', 'core', 'bodyweight'),
  ('Hanging Leg Raise', 'core', 'bodyweight'),
  ('Russian Twist', 'core', 'bodyweight');
